/**
 * DSL element type constants.
 * Used internally by ViewBuilder and DSLRenderer to identify component types.
 */
export enum ElementType {
  text = 'text',
  vstack = 'vstack',
  hstack = 'hstack',
  zstack = 'zstack',
  icon = 'icon',
  spacer = 'spacer',
  raw = 'raw',
  fragment = 'fragment',
  safearea = 'safearea',
  scroll = 'scroll',
  textinput = 'textinput',
  spinner = 'spinner',
  lazylist = 'lazylist',
  image = 'image',
  toggle = 'toggle',
  button = 'button',
  divider = 'divider',
  link = 'link',
  sectionlist = 'sectionlist',
  modal = 'modal',
  progressbar = 'progressbar',
}

export type ElementTypeValue = `${ElementType}`;

/**
 * Gesture type discriminants for GestureConfig.
 */
export enum GestureType {
  swipe = 'swipe',
  pan = 'pan',
  pinch = 'pinch',
  rotation = 'rotation',
}

export type GestureTypeValue = `${GestureType}`;

/**
 * Modifier type discriminants.
 */
export enum ModifierType {
  padding = 'padding',
  margin = 'margin',
  background = 'background',
  backgroundAlpha = 'backgroundAlpha',
  foregroundColor = 'foregroundColor',
  cornerRadius = 'cornerRadius',
  font = 'font',
  fontWeight = 'fontWeight',
  flex = 'flex',
  frame = 'frame',
  border = 'border',
  borderStyle = 'borderStyle',
  shadow = 'shadow',
  opacity = 'opacity',
  spacing = 'spacing',
  alignment = 'alignment',
  justifyContent = 'justifyContent',
  alignItems = 'alignItems',
  flexWrap = 'flexWrap',
  gap = 'gap',
  textTransform = 'textTransform',
  letterSpacing = 'letterSpacing',
  lineHeight = 'lineHeight',
  textAlign = 'textAlign',
  lineLimit = 'lineLimit',
  onTap = 'onTap',
  onLongPress = 'onLongPress',
  disabled = 'disabled',
  accessibilityLabel = 'accessibilityLabel',
  accessibilityRole = 'accessibilityRole',
  accessibilityHint = 'accessibilityHint',
  testID = 'testID',
  safeAreaEdges = 'safeAreaEdges',
  hideScrollIndicator = 'hideScrollIndicator',
  scrollContentPadding = 'scrollContentPadding',
  scrollDirection = 'scrollDirection',
  keyboardAvoiding = 'keyboardAvoiding',
  keyboardPersistTaps = 'keyboardPersistTaps',
  bounces = 'bounces',
  placeholder = 'placeholder',
  inputLabel = 'inputLabel',
  inputError = 'inputError',
  keyboardType = 'keyboardType',
  multiline = 'multiline',
  secureEntry = 'secureEntry',
  autoCapitalize = 'autoCapitalize',
  returnKeyType = 'returnKeyType',
  maxLength = 'maxLength',
  inputHeight = 'inputHeight',
  inputRef = 'inputRef',
  onSubmitEditing = 'onSubmitEditing',
  screenTitle = 'screenTitle',
  headerRight = 'headerRight',
  headerLeft = 'headerLeft',
  position = 'position',
  positionEdges = 'positionEdges',
  zIndex = 'zIndex',
  overflow = 'overflow',
  aspectRatio = 'aspectRatio',
  alignSelf = 'alignSelf',
  display = 'display',
  hidden = 'hidden',
  textDecoration = 'textDecoration',
  fontStyle = 'fontStyle',
  fontFamily = 'fontFamily',
  refreshControl = 'refreshControl',
  onEndReached = 'onEndReached',
  separator = 'separator',
  numColumns = 'numColumns',
  emptyComponent = 'emptyComponent',
  onDismiss = 'onDismiss',
  offset = 'offset',
  rotation = 'rotation',
  scale = 'scale',
  blur = 'blur',
  overlay = 'overlay',
  onIOS = 'onIOS',
  onAndroid = 'onAndroid',
  responsive = 'responsive',
  onCompact = 'onCompact',
  onRegular = 'onRegular',
  onLarge = 'onLarge',
  animation = 'animation',
  transition = 'transition',
  onSwipe = 'onSwipe',
  onPan = 'onPan',
  onPinch = 'onPinch',
  onRotate = 'onRotate',
  gesture = 'gesture',
  environment = 'environment',
}

export type ModifierTypeValue = `${ModifierType}`;
